@props(['action'])

@php
    $inputClass = 'min-w-0 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium text-slate-800 shadow-sm outline-none transition placeholder:text-slate-400 focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100';
    $sectionClass = 'flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2 text-sm font-black uppercase tracking-wide text-white shadow-md shadow-emerald-700/15';
@endphp

<form method="POST" action="{{ $action }}" enctype="multipart/form-data" data-location-form data-branch-location-form data-upazilas='@json(config("bangladesh.upazilas"))' data-old-upazila="{{ old('upazila') }}" data-old-post-office="{{ old('post_office') }}" class="space-y-7 rounded-[2rem] border border-slate-200 bg-white p-5 shadow-[0_20px_70px_rgb(15_23_42/0.08)] sm:p-8">
    @csrf

    <section class="min-w-0 space-y-5">
        <h2 class="{{ $sectionClass }}"><svg viewBox="0 0 24 24" class="size-5 fill-none stroke-current" aria-hidden="true" stroke-width="1.8"><path d="M4 21V5a2 2 0 0 1 2-2h8v18"/><path d="M14 9h6v12h-6zM8 7h2M8 11h2M8 15h2"/></svg>Institute Information</h2>
        <div class="grid gap-5 md:grid-cols-2">
            <label class="block min-w-0 text-sm font-bold text-slate-700">Institute Name <span class="text-rose-600">*</span><input name="institute_name" value="{{ old('institute_name') }}" required placeholder="Enter institute name" class="{{ $inputClass }} mt-2">@error('institute_name')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label>
            <label class="block min-w-0 text-sm font-bold text-slate-700">E-mail <span class="text-rose-600">*</span><input type="email" name="email" value="{{ old('email') }}" required placeholder="Enter official email" class="{{ $inputClass }} mt-2">@error('email')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label>
        </div>
    </section>

    <div class="grid items-start gap-8 lg:grid-cols-[minmax(0,.9fr)_minmax(0,1.2fr)_minmax(260px,.85fr)]">
        <section class="min-w-0 space-y-5">
            <h2 class="{{ $sectionClass }}"><svg viewBox="0 0 24 24" class="size-5 fill-none stroke-current" aria-hidden="true" stroke-width="1.8"><circle cx="12" cy="8" r="3"/><path d="M5 21c.5-4 2.8-6 7-6s6.5 2 7 6"/></svg>Director Information</h2>
            @foreach (['director_name' => 'Director Name', 'father_name' => "Father's Name", 'mother_name' => "Mother's Name"] as $field => $label)
                <label class="block text-sm font-bold text-slate-700 {{ $loop->iteration === 2 ? 'lg:mt-16' : '' }}">{{ $label }} <span class="text-rose-600">*</span><input name="{{ $field }}" value="{{ old($field) }}" required placeholder="Enter {{ strtolower($label) }}" class="{{ $inputClass }} mt-2">@error($field)<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label>
            @endforeach
            <label class="block text-sm font-bold text-slate-700">Sex <span class="text-rose-600">*</span><select name="sex" required class="{{ $inputClass }} mt-2"><option value="">Select sex</option>@foreach(['Male','Female','Other'] as $sex)<option value="{{ $sex }}" @selected(old('sex') === $sex)>{{ $sex }}</option>@endforeach</select>@error('sex')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label>
            <label class="block text-sm font-bold text-slate-700 lg:-mt-3">Mobile Number <span class="text-rose-600">*</span><input type="tel" name="mobile_number" value="{{ old('mobile_number') }}" required placeholder="Enter mobile number" class="{{ $inputClass }} mt-2">@error('mobile_number')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label>
        </section>

        <section class="min-w-0 space-y-5">
            <h2 class="{{ $sectionClass }}"><svg viewBox="0 0 24 24" class="size-5 fill-none stroke-current" aria-hidden="true" stroke-width="1.8"><path d="M12 21s7-6.1 7-12a7 7 0 1 0-14 0c0 5.9 7 12 7 12Z"/><circle cx="12" cy="9" r="2.2"/></svg>Address Information</h2>
            <label class="block text-sm font-bold text-slate-700">Full Address <span class="text-rose-600">*</span><textarea name="full_address" rows="3" required placeholder="Enter full address" class="{{ $inputClass }} mt-2">{{ old('full_address') }}</textarea>@error('full_address')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label>
            <div class="grid gap-4 sm:grid-cols-2"><label class="block min-w-0 text-sm font-bold text-slate-700">District <span class="text-rose-600">*</span><select name="district" data-district-select required class="{{ $inputClass }} mt-2"><option value="">Select district</option>@foreach (config('bangladesh.districts') as $district)<option value="{{ $district }}" @selected(old('district') === $district)>{{ $district }}</option>@endforeach</select>@error('district')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label><label class="block min-w-0 text-sm font-bold text-slate-700">Upazila <span class="text-rose-600">*</span><select name="upazila" data-upazila-select required disabled class="{{ $inputClass }} mt-2"><option value="">Select district first</option></select>@error('upazila')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label></div>
            <label class="block text-sm font-bold text-slate-700">Post Office <span class="text-rose-600">*</span><select name="post_office" data-post-office-select required disabled class="{{ $inputClass }} mt-2"><option value="">Select upazila first</option></select>@error('post_office')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label>

            <div class="border-t border-slate-200 pt-6"><h2 class="{{ $sectionClass }}"><svg viewBox="0 0 24 24" class="size-5 fill-none stroke-current" aria-hidden="true" stroke-width="1.8"><rect x="4" y="10" width="16" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>Login Credentials</h2></div>
            <div class="grid gap-4 sm:grid-cols-3"><label class="block min-w-0 text-sm font-bold text-slate-700 sm:col-span-3">Username <span class="text-rose-600">*</span><input name="username" value="{{ old('username') }}" required placeholder="Choose username" class="{{ $inputClass }} mt-2">@error('username')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label><label class="block min-w-0 text-sm font-bold text-slate-700 sm:col-span-3">Password <span class="text-rose-600">*</span><input type="password" name="password" required minlength="8" placeholder="Minimum 8 characters" class="{{ $inputClass }} mt-2">@error('password')<span class="mt-1 block text-rose-600">{{ $message }}</span>@enderror</label><label class="block min-w-0 text-sm font-bold text-slate-700 sm:col-span-3">Confirm Password <span class="text-rose-600">*</span><input type="password" name="password_confirmation" required minlength="8" placeholder="Repeat password" class="{{ $inputClass }} mt-2"></label></div>
        </section>

        <aside class="min-w-0 space-y-6">
            <section class="space-y-5"><h2 class="{{ $sectionClass }}"><svg viewBox="0 0 24 24" class="size-5 fill-none stroke-current" aria-hidden="true" stroke-width="1.8"><path d="M4 7h4l1.5-2h5L16 7h4v12H4z"/><circle cx="12" cy="13" r="3.5"/></svg>Required Documents</h2><div class="grid gap-4">@foreach(['director_signature' => ['Director Signature', 'Max 2MB'], 'nid_photo' => ['NID Photo', 'Max 4MB'], 'director_photo' => ['Director Photo', 'Max 4MB']] as $field => [$label, $hint])<label class="grid min-h-40 cursor-pointer place-items-center gap-2 rounded-2xl border-2 border-dashed border-emerald-200 bg-emerald-50/40 p-4 text-center transition hover:border-emerald-500"><span class="mx-auto grid size-12 place-items-center rounded-full bg-emerald-100 text-emerald-700"><svg viewBox="0 0 24 24" class="size-6 fill-none stroke-current" aria-hidden="true" stroke-width="1.8"><path d="M12 16V4m0 0L8 8m4-4 4 4M5 14v5h14v-5"/></svg></span><span><strong class="block text-sm text-slate-800">{{ $label }}</strong><small class="text-xs text-slate-500">JPG / PNG / WebP · {{ $hint }}</small></span><input type="file" name="{{ $field }}" required accept="image/jpeg,image/png,image/webp" class="sr-only">@error($field)<span class="text-sm text-rose-600">{{ $message }}</span>@enderror</label>@endforeach</div></section>
            <section class="rounded-2xl bg-gradient-to-br from-emerald-800 to-green-700 p-6 text-white shadow-lg"><h2 class="flex items-center gap-2 text-sm font-black uppercase tracking-wide"><svg viewBox="0 0 24 24" class="size-6 fill-none stroke-current" aria-hidden="true" stroke-width="1.8"><path d="M12 3a5 5 0 0 1 5 5c0 3-2 4-2 6H9c0-2-2-3-2-6a5 5 0 0 1 5-5ZM9 18h6M10 21h4"/><path d="M12 1v2M4.9 4.9 6.3 6.3M19.1 4.9 17.7 6.3"/></svg>Important Notes</h2><ul class="mt-5 grid gap-3 text-sm font-medium leading-5 text-emerald-50"><li>✓ Complete every required field.</li><li>✓ Provide accurate institute information.</li><li>✓ Upload clear, readable documents.</li><li>✓ Keep your login details secure.</li></ul></section>
        </aside>
    </div>
    <div class="flex flex-col justify-center gap-3 border-t border-slate-200 pt-6 sm:flex-row"><button class="inline-flex min-h-14 items-center justify-center gap-3 rounded-xl bg-gradient-to-r from-green-600 to-emerald-700 px-8 font-black text-white shadow-lg shadow-emerald-700/20 transition hover:-translate-y-0.5 hover:from-green-500 hover:to-emerald-600">APPLICATION SUBMIT</button><button type="reset" class="inline-flex min-h-14 items-center justify-center gap-3 rounded-xl border-2 border-slate-300 bg-white px-8 font-black text-slate-800 transition hover:border-emerald-600 hover:text-emerald-700">↻ RESET FORM</button></div>
</form>
