<x-dashboard-shell title="Departments & Courses" eyebrow="Academic Management" description="Manage the programs offered by the institute and open each one to organize its semesters.">
    <x-slot:actions><a href="{{ route('super-admin.courses.create') }}" class="admin-button admin-button--primary">Create a course</a></x-slot:actions>
    <x-admin-filter-bar :search="$search" :status="$selectedStatus" :statuses="['active' => 'Active', 'inactive' => 'Inactive']" placeholder="Search departments and courses" />
    @if($courses->isEmpty())
        <div class="admin-panel"><x-admin-empty-state title="No courses created yet" description="Create a department or course before adding semesters, subjects, and students." action-label="Create a course" :action-url="route('super-admin.courses.create')" /></div>
    @else
        <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($courses as $course)<article class="admin-panel flex flex-col"><div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-black text-slate-950">{{ $course->name }}</h2><p class="mt-1 text-sm font-semibold text-slate-500">Duration: {{ $course->duration }}</p></div><x-admin-status :status="$course->is_active ? 'active' : 'inactive'" /></div><p class="mt-4 line-clamp-3 text-sm leading-6 text-slate-600">{{ $course->description ?: 'No course description has been added.' }}</p><div class="mt-auto flex flex-wrap gap-2 border-t border-slate-100 pt-5"><a href="{{ route('super-admin.courses.semesters.index', $course) }}" class="admin-button admin-button--primary">Manage semesters</a><a href="{{ route('super-admin.courses.edit', $course) }}" class="admin-button admin-button--secondary">Edit</a><form method="POST" action="{{ route('super-admin.courses.destroy', $course) }}" data-confirm="Delete this course? This action cannot be undone.">@csrf @method('DELETE')<button class="admin-button admin-button--danger">Delete</button></form></div></article>@endforeach</div><div class="mt-6">{{ $courses->links() }}</div>
    @endif
</x-dashboard-shell>
