<x-dashboard-shell :title="isset($result) ? 'Edit Marks' : 'Enter Marks'" eyebrow="Result management" :description="$enrollment->student->name.' · '.$enrollment->semester->name">
    <form method="POST" action="{{ route('super-admin.enrollments.results.store', $enrollment) }}" class="space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        @csrf
        <div class="grid gap-5 sm:grid-cols-2">
            <label class="grid gap-2 text-sm font-bold text-slate-700">Session<input name="session" required value="{{ old('session', $result->session ?? now()->year) }}" class="rounded-xl border border-slate-300 px-3 py-2.5"></label>
            <label class="grid gap-2 text-sm font-bold text-slate-700">Status<select name="status" class="w-full rounded-xl border border-slate-300 px-3 py-2.5"><option value="draft" @selected(old('status', $result->status ?? 'draft') === 'draft')>Draft</option><option value="published" @selected(old('status', $result->status ?? 'draft') === 'published')>Published</option></select></label>
        </div>
        <div><h2 class="text-lg font-black">Subject marks</h2><p class="mt-1 text-sm text-slate-500">Enter marks from 0 to 100. Grade and grade point are calculated automatically.</p><div class="mt-4 overflow-x-auto rounded-xl border border-slate-200"><table class="w-full min-w-[700px] text-left text-sm"><thead class="bg-slate-50 text-xs font-black uppercase text-slate-500"><tr><th class="px-4 py-3">Code</th><th class="px-4 py-3">Subject</th><th class="px-4 py-3">Credit</th><th class="px-4 py-3">Marks</th><th class="px-4 py-3">Grade</th><th class="px-4 py-3">Point</th></tr></thead><tbody>@foreach ($enrollment->subjects as $subject) @php $saved = isset($result) ? $result->subjects->firstWhere('code', $subject->code) : null; @endphp<tr><td class="border-t px-4 py-3 font-black">{{ $subject->code }}<input type="hidden" name="subjects[{{ $loop->index }}][id]" value="{{ $subject->id }}"></td><td class="border-t px-4 py-3">{{ $subject->title }}</td><td class="border-t px-4 py-3">{{ $subject->credit }}</td><td class="border-t px-4 py-3"><input type="number" name="subjects[{{ $loop->index }}][marks]" min="0" max="100" step="0.01" value="{{ old('subjects.'.$loop->index.'.marks', $saved?->marks) }}" class="w-32 rounded-lg border border-slate-300 px-3 py-2"></td><td class="border-t px-4 py-3 font-black">{{ $saved?->grade ?? '—' }}</td><td class="border-t px-4 py-3">{{ $saved?->grade_point !== null ? number_format((float) $saved->grade_point, 2) : '—' }}</td></tr>@endforeach</tbody></table></div></div>
        <div class="flex justify-end gap-3"><a href="{{ route('super-admin.students.semester-enrollments.index', $enrollment->student) }}" class="rounded-full border border-slate-300 px-5 py-3 font-black text-slate-700">Cancel</a><button class="rounded-full bg-blue-600 px-5 py-3 font-black text-white">Save marks</button></div>
    </form>
</x-dashboard-shell>
