<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="theme-color" content="#15803d">
        <title>Branch Registration | BNYTI</title>
        <link rel="icon" href="{{ asset('images/bnyti-logo.svg') }}" type="image/svg+xml">
        @fonts
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="min-h-screen overflow-x-hidden bg-stone-50 text-slate-900 antialiased dark:bg-ink dark:text-white">
        <a href="#main-content" class="fixed top-3 left-3 z-[100] -translate-y-20 rounded-full bg-emerald-500 px-5 py-3 text-sm font-bold text-ink transition focus:translate-y-0">Skip to content</a>
        <header class="border-b border-slate-900/5 bg-stone-50/95 backdrop-blur-xl dark:border-white/10 dark:bg-ink/95">
            <div class="border-b border-slate-900/5 bg-ink text-white dark:border-white/10"><div class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-2 text-[11px] font-semibold tracking-wide sm:px-6 lg:px-8"><p class="flex items-center gap-2"><span class="size-1.5 rounded-full bg-emerald-400"></span>Branch applications are open nationwide</p><div class="hidden gap-5 sm:flex"><a href="tel:+8809696481628" class="hover:text-emerald-300">+880 9696-481628</a><a href="mailto:bnyti-edubd@gmail.com" class="hover:text-emerald-300">bnyti-edubd@gmail.com</a></div></div></div>
            <div class="mx-auto flex h-[76px] max-w-7xl items-center justify-between gap-5 px-4 sm:px-6 lg:px-8"><a href="{{ route('home') }}" class="group flex min-w-0 items-center gap-3"><img src="{{ asset('images/bnyti-logo.svg') }}" alt="Bangladesh National Youth Technical Institute logo" class="brand-logo size-12 shrink-0 sm:size-14"><span class="hidden min-w-0 sm:block"><span class="block text-sm font-black tracking-tight text-slate-950 dark:text-white sm:text-[15px]"><span class="text-emerald-600">BANGLADESH</span><span class="text-red-600"> NATIONAL</span></span><span class="block text-[10px] font-bold tracking-[.17em] text-slate-600 dark:text-slate-300">YOUTH TECHNICAL INSTITUTE</span></span><span class="sm:hidden"><span class="block text-base font-black text-slate-950 dark:text-white">BNYTI</span><span class="block text-[9px] font-bold tracking-[.14em] text-slate-500">TECHNICAL INSTITUTE</span></span></a><nav class="hidden items-center gap-7 lg:flex" aria-label="Primary navigation"><a href="{{ route('home') }}#home" class="nav-link">Home</a><a href="{{ route('home') }}#courses" class="nav-link">Courses</a><a href="{{ route('home') }}#about" class="nav-link">About</a><a href="{{ route('home') }}#branch-application-promo" class="nav-link">Branches</a><a href="{{ route('branch-applications.create') }}" class="nav-link active" aria-current="page">Branch Register</a><a href="{{ route('student-registrations.create') }}" class="nav-link">Student Register</a><a href="{{ route('results.index') }}" class="nav-link">Student Results</a></nav><div class="flex shrink-0 items-center gap-2"><button type="button" class="icon-button" data-locale-toggle aria-label="Switch language"><span class="text-xs font-black" data-locale-label>বাংলা</span></button><button type="button" class="icon-button" data-theme-toggle aria-label="Toggle theme"><svg data-theme-sun viewBox="0 0 24 24" class="size-5"><circle cx="12" cy="12" r="4" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M12 2v2M12 20v2M2 12h2m16 0h2" fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="1.8"/></svg><svg data-theme-moon viewBox="0 0 24 24" class="hidden size-5"><path d="M20 15.1A8.5 8.5 0 0 1 8.9 4a8.5 8.5 0 1 0 11.1 11.1Z" fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="1.8"/></svg></button><button type="button" class="icon-button lg:hidden" data-menu-toggle aria-expanded="false" aria-controls="branch-mobile-menu" aria-label="Open menu"><svg data-menu-open viewBox="0 0 24 24" class="size-6"><path d="M4 7h16M4 12h16M4 17h16" fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2"/></svg><svg data-menu-close viewBox="0 0 24 24" class="hidden size-6"><path d="m6 6 12 12M18 6 6 18" fill="none" stroke="currentColor" stroke-linecap="round" stroke-width="2"/></svg></button></div></div>
            <div id="branch-mobile-menu" class="border-t border-slate-900/5 bg-stone-50 px-4 py-5 shadow-2xl dark:border-white/10 dark:bg-ink lg:hidden" data-mobile-menu hidden><nav class="mx-auto grid max-w-7xl gap-1" aria-label="Mobile navigation"><a href="{{ route('home') }}#home" class="mobile-nav-link">Home</a><a href="{{ route('home') }}#courses" class="mobile-nav-link">Courses</a><a href="{{ route('home') }}#about" class="mobile-nav-link">About</a><a href="{{ route('home') }}#branch-application-promo" class="mobile-nav-link">Branches</a><a href="{{ route('branch-applications.create') }}" class="mobile-nav-link bg-emerald-500/10 text-emerald-700" aria-current="page">Branch Register</a><a href="{{ route('student-registrations.create') }}" class="mobile-nav-link">Student Register</a><a href="{{ route('results.index') }}" class="mobile-nav-link">Student Results</a></nav></div>
        </header>

        <main id="main-content" class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
            <section class="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-emerald-950 via-green-800 to-emerald-700 px-6 py-8 text-white shadow-2xl sm:px-10 sm:py-12 lg:px-14"><div class="absolute -right-20 -top-24 size-72 rounded-full border-[40px] border-emerald-300/10"></div><div class="relative grid items-center gap-8 lg:grid-cols-[1fr_auto_1fr]"><div class="flex items-center gap-4"><img src="{{ asset('images/bnyti-logo.svg') }}" alt="BNYTI logo" class="size-20 rounded-full bg-white p-1 shadow-lg sm:size-28"><div><p class="text-lg font-black uppercase tracking-wide sm:text-2xl">Bangladesh National Youth</p><p class="text-sm font-bold uppercase tracking-[.12em] text-emerald-200 sm:text-base">Technical Institute</p><p class="mt-2 text-xs text-emerald-100">Empowering Youth, Building Future</p></div></div><div class="text-center"><div class="mb-3 text-emerald-200">◆</div><h1 class="text-3xl font-black uppercase tracking-tight sm:text-5xl">Branch Registration</h1><p class="mt-3 font-medium text-emerald-100">Build Your Future With BNYTI</p></div><div class="hidden justify-self-end rounded-2xl border border-white/20 bg-white/10 p-5 text-right backdrop-blur sm:block"><p class="text-xs font-bold uppercase tracking-widest text-emerald-200">{{ now()->format('d F Y') }}</p><p class="mt-2 text-lg font-black">{{ now()->format('l') }}</p><p class="mt-1 text-sm text-emerald-100">{{ now()->format('h:i A') }} · Local Time</p></div></div><div class="relative mt-8 grid gap-3 rounded-2xl border border-white/20 bg-white/10 p-4 text-center backdrop-blur sm:grid-cols-4">@foreach ([['Secure Registration', 'Your information is safe'], ['Verified Partnership', 'Government approved'], ['Approved Branch', 'Trusted learning center'], ['Nationwide Network', '250+ branches across Bangladesh']] as [$title, $body])<div class="border-white/15 px-3 sm:border-r sm:last:border-r-0"><p class="text-xs font-black uppercase tracking-wide">{{ $title }}</p><p class="mt-1 text-xs text-emerald-100">{{ $body }}</p></div>@endforeach</div></section>
            @if (session('status'))<div class="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 font-bold text-emerald-800">{{ session('status') }}</div>@endif
            <div class="mt-7"><x-branch-application-form :action="route('branch-applications.store')" /></div>
        </main>
        <footer class="mt-8 bg-emerald-950 text-white"><div class="mx-auto grid max-w-7xl gap-4 px-4 py-7 sm:grid-cols-2 sm:px-6 lg:grid-cols-4 lg:px-8">@foreach ([['Trusted & Verified', 'Government Registered'], ['Quality Technical Education', 'Practical & Skill Based'], ['Nationwide Network', '250+ branches across Bangladesh'], ['Support 24/7', '+880 9696-481628']] as [$title, $body])<div class="flex items-center gap-3 border-white/15 sm:border-r sm:last:border-r-0"><span class="grid size-10 shrink-0 place-items-center rounded-full bg-emerald-700 text-emerald-100">✓</span><span><strong class="block text-sm">{{ $title }}</strong><small class="text-emerald-200">{{ $body }}</small></span></div>@endforeach</div><div class="border-t border-white/10 px-4 py-4 text-center text-xs text-emerald-200">© {{ date('Y') }} Bangladesh National Youth Technical Institute. All rights reserved.</div></footer>
    </body>
</html>
