<x-dashboard-shell title="Branch Approvals" eyebrow="People & Branches" description="Review applications and decide which branches may access the institute system.">
    <form method="GET" class="admin-panel mb-5 flex flex-col gap-3 sm:flex-row" aria-label="Filter branch applications">
        <label class="flex-1"><span class="sr-only">Search applications</span><input name="search" value="{{ $search }}" placeholder="Search institute, director, or district" class="min-h-11 w-full rounded-xl border border-slate-300 px-4 text-sm"></label>
        <label><span class="sr-only">Application status</span><select name="status" class="min-h-11 w-full rounded-xl border border-slate-300 px-4 text-sm sm:w-44"><option value="">All statuses</option>@foreach(\App\Enums\BranchApplicationStatus::cases() as $status)<option value="{{ $status->value }}" @selected($selectedStatus === $status->value)>{{ $status->label() }}</option>@endforeach</select></label>
        <button class="admin-button admin-button--primary">Apply filters</button>
        @if($search || $selectedStatus)<a href="{{ route('super-admin.branch-applications.index') }}" class="admin-button admin-button--secondary">Clear</a>@endif
    </form>
    @if($applications->isEmpty())
        <div class="admin-panel"><x-admin-empty-state title="No branch applications found" description="Try clearing the filters, or return later when a new branch registration is submitted." /></div>
    @else
        <div class="admin-table-wrap"><div class="overflow-x-auto"><table class="admin-table"><caption class="sr-only">Branch applications awaiting or completing review</caption><thead><tr><th>Institute</th><th>Director</th><th>District</th><th>Submitted</th><th>Status</th><th class="text-right">Next step</th></tr></thead><tbody>@foreach($applications as $application)<tr><td><p class="font-black text-slate-950">{{ $application->institute_name ?? $application->proposed_branch_name }}</p><p class="mt-1 text-xs text-slate-500">{{ $application->email }}</p></td><td class="text-sm font-semibold text-slate-700">{{ $application->director_name ?? $application->applicant_name }}</td><td class="text-sm text-slate-600">{{ $application->district }}</td><td class="text-sm text-slate-600">{{ $application->created_at->format('d M Y') }}</td><td><x-admin-status :status="$application->status" /></td><td class="text-right"><a href="{{ route('super-admin.branch-applications.show', $application) }}" class="admin-button admin-button--secondary">{{ $application->status->value === 'pending' ? 'Review application' : 'View decision' }}</a></td></tr>@endforeach</tbody></table></div></div><div class="mt-6">{{ $applications->links() }}</div>
    @endif
</x-dashboard-shell>
