<x-dashboard-shell :title="$branchApplication->institute_name ?? $branchApplication->proposed_branch_name" eyebrow="Branch approval review" description="Check the applicant details and supporting documents before making a decision." :breadcrumbs="['Branch Approvals' => route('super-admin.branch-applications.index'), 'Application review' => null]">
    <x-slot:actions><a href="{{ route('super-admin.branch-applications.index') }}" class="admin-button admin-button--secondary">Back to applications</a></x-slot:actions>
    <div class="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-5"><div><p class="text-sm font-bold text-slate-500">Current application status</p><div class="mt-2"><x-admin-status :status="$branchApplication->status" /></div></div><div class="text-left sm:text-right"><p class="text-sm font-bold text-slate-500">Submitted</p><p class="mt-1 font-black text-slate-900">{{ $branchApplication->created_at->format('d F Y, h:i A') }}</p></div></div>
    <div class="grid gap-6 xl:grid-cols-[1fr_22rem]">
        <div class="space-y-6">
            <section class="admin-panel"><h2 class="text-lg font-black text-slate-950">Applicant and institute details</h2><p class="mt-1 text-sm text-slate-600">Confirm these details match the uploaded identification.</p><dl class="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">@foreach(['director_name' => 'Director name', 'father_name' => "Father's name", 'mother_name' => "Mother's name", 'institute_name' => 'Institute name', 'district' => 'District', 'upazila' => 'Upazila', 'post_office' => 'Post office', 'email' => 'Email address', 'sex' => 'Gender', 'username' => 'Requested username', 'mobile_number' => 'Mobile number'] as $field => $label)<div><dt class="text-xs font-black uppercase tracking-wide text-slate-500">{{ $label }}</dt><dd class="mt-1 break-words font-bold text-slate-900">{{ $branchApplication->{$field} ?? 'Not provided' }}</dd></div>@endforeach<div class="sm:col-span-2 lg:col-span-3"><dt class="text-xs font-black uppercase tracking-wide text-slate-500">Full address</dt><dd class="mt-1 leading-7 text-slate-800">{{ $branchApplication->full_address ?? $branchApplication->address ?? 'Not provided' }}</dd></div></dl></section>
            <section class="admin-panel"><h2 class="text-lg font-black text-slate-950">Supporting documents</h2><p class="mt-1 text-sm text-slate-600">Open each image and verify that it is clear and belongs to the applicant.</p><div class="mt-5 grid gap-5 sm:grid-cols-3">@foreach(['director_photo_path' => 'Director photo', 'nid_photo_path' => 'NID photo', 'director_signature_path' => 'Director signature'] as $field => $label)<article class="rounded-xl border border-slate-200 p-3"><p class="text-sm font-black text-slate-800">{{ $label }}</p>@if($branchApplication->{$field})<a href="{{ Storage::disk('public')->url($branchApplication->{$field}) }}" target="_blank" rel="noopener" class="mt-3 block"><img src="{{ Storage::disk('public')->url($branchApplication->{$field}) }}" alt="{{ $label }}" class="h-40 w-full rounded-lg bg-slate-50 object-contain"><span class="mt-2 block text-xs font-black text-blue-700">Open full image ↗</span></a>@else<p class="mt-3 rounded-lg bg-amber-50 p-4 text-sm font-bold text-amber-800">Not uploaded</p>@endif</article>@endforeach</div></section>
        </div>
        <aside class="space-y-5">
            @if($branchApplication->status->value === 'pending')
                <section class="admin-panel border-emerald-200"><h2 class="text-lg font-black text-slate-950">Approve branch</h2><p class="mt-2 text-sm leading-6 text-slate-600">Approval creates a branch login account and allows authorized student registration.</p><form method="POST" action="{{ route('super-admin.branch-applications.update', $branchApplication) }}" class="mt-5" data-confirm="Approve this branch and create its login account?">@csrf @method('PATCH')<input type="hidden" name="status" value="approved"><button class="admin-button admin-button--success w-full">Approve and activate</button></form></section>
                <section class="admin-panel border-rose-200"><h2 class="text-lg font-black text-slate-950">Reject application</h2><p class="mt-2 text-sm leading-6 text-slate-600">Give a clear reason the applicant can understand and correct.</p><form method="POST" action="{{ route('super-admin.branch-applications.update', $branchApplication) }}" class="mt-4" data-confirm="Reject this branch application?">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><label class="text-sm font-black text-slate-800">Rejection reason <span class="text-rose-700">Required</span><textarea name="rejection_reason" required rows="4" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-sm" placeholder="Explain what is missing or incorrect.">{{ old('rejection_reason') }}</textarea></label><button class="admin-button admin-button--danger mt-4 w-full">Reject application</button></form></section>
            @else
                <section class="admin-panel"><h2 class="text-lg font-black text-slate-950">Review completed</h2><p class="mt-3 text-sm leading-6 text-slate-600">Decision recorded {{ $branchApplication->reviewed_at?->diffForHumans() ?? 'previously' }}.</p>@if($branchApplication->rejection_reason)<div class="mt-4 rounded-xl bg-rose-50 p-4"><p class="text-xs font-black uppercase text-rose-700">Rejection reason</p><p class="mt-2 text-sm leading-6 text-rose-950">{{ $branchApplication->rejection_reason }}</p></div>@endif</section>
            @endif
        </aside>
    </div>
</x-dashboard-shell>
