<x-dashboard-shell title="{{ $section->label }}" eyebrow="Homepage CMS" description="Manage published homepage content for this section.">
    <div class="mb-6 flex flex-wrap items-center justify-between gap-4">
        <div>
            <p class="text-sm text-slate-500">{{ $items->total() }} items</p>
            <form class="mt-3 flex items-center gap-3" method="POST" action="{{ route('super-admin.homepage.sections.update', $section) }}">@csrf @method('PATCH')<label class="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="is_visible" value="1" @checked($section->is_visible)> Visible</label><input class="w-24 rounded-lg border-slate-300 px-3 py-2 text-sm" type="number" name="sort_order" value="{{ $section->sort_order }}" min="0"><button class="rounded-lg bg-slate-900 px-3 py-2 text-xs font-black text-white">Save section</button></form>
        </div>
        <a href="{{ route('super-admin.homepage.items.create', $section->key) }}" class="rounded-full bg-blue-600 px-5 py-3 font-black text-white">Add item</a>
    </div>
    @if(session('status'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 font-bold text-emerald-800">{{ session('status') }}</div>@endif
    @if($section->key === 'contact' && ($contactItem = $items->first()) && data_get($contactItem->metadata, 'map_url'))
        <div class="mb-6 rounded-2xl border border-blue-100 bg-blue-50 p-5"><p class="text-sm font-black text-blue-900">Google Maps location</p><a class="mt-2 inline-flex font-bold text-blue-700 hover:underline" href="{{ data_get($contactItem->metadata, 'map_url') }}" target="_blank" rel="noopener noreferrer">Open location in Google Maps →</a></div>
    @endif
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left"><thead class="bg-slate-50 text-xs font-black uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Title</th><th class="px-5 py-4">Subtitle</th><th class="px-5 py-4">Image</th><th class="px-5 py-4">Body</th><th class="px-5 py-4">Order</th><th class="px-5 py-4">Status</th><th class="px-5 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($items as $item)<tr><td class="px-5 py-4"><p class="font-black">{{ $item->title }}</p><p class="text-xs text-slate-400">{{ $item->stable_key }}</p></td><td class="max-w-[240px] px-5 py-4 text-sm font-semibold text-slate-700">{{ $item->subtitle ?: '—' }}</td><td class="px-5 py-4">@if($item->image_path)<img src="{{ str_starts_with($item->image_path, 'images/') ? asset($item->image_path) : Storage::disk('public')->url($item->image_path) }}" alt="{{ $item->title }}" class="h-16 w-28 rounded-lg object-cover">@else<span class="text-sm text-slate-400">No image</span>@endif</td><td class="max-w-[360px] px-5 py-4 text-sm text-slate-600">{{ Str::limit($item->body, 120) }}</td><td class="px-5 py-4 font-black">{{ $item->sort_order }}</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-black {{ $item->is_published ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ $item->is_published ? 'Published' : 'Draft' }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('super-admin.homepage.items.edit', $item) }}" class="font-black text-emerald-700">Edit</a><form class="ml-3 inline" method="POST" action="{{ route('super-admin.homepage.items.destroy', $item) }}" onsubmit="return confirm('Delete this homepage item?')">@csrf @method('DELETE')<button class="font-black text-rose-600">Delete</button></form></td></tr>@empty<tr><td colspan="7" class="px-6 py-12 text-center text-slate-500">No homepage items yet.</td></tr>@endforelse</tbody></table></div></div><div class="mt-6">{{ $items->links() }}</div>
</x-dashboard-shell>
